services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  worker:
    build: .
    env_file:
      - .env
    ports:
      - '9100:9100'  # Prometheus metrics
      - '3000:3000'  # Dashboard

volumes:
  pgdata: 